REGD-67 adding package.json and updating sequence_logo.js to the latest currently in regulome libs
ENCODE-DCC/d3-sequence-logo pull request #3
Opened 2022-09-07 22:57 UTC by dougli1sqrd

2022-09-07 23:07 UTC, hitz requested changes

2022-09-07 23:07 UTC, hitz commented on package.json
> +    "url": "https://github.com/splichte/d3-sequence-logo"
this should be our fork!

2022-09-19 16:29 UTC, dougli1sqrd commented
I've verified that this works as an npm package dependency of regulome, so this is ready to be merged

2022-09-19 18:07 UTC, hitz approved these changes

2022-09-19 18:10 UTC, merged